## Lit Review

@Czarnitzki2023 Using survey data on German firms, the authors find a positive and significant association between the use of AI and firm productivity. Authors use a production function approach, but they cannot use popular method of production functions because their data is only a cross-section of german firms and a very small panel. Their measure of AI are indicators (e.g. whether they use or not AI) and some measures of intensity of AI usage. The authors define AI broadly because the 2019 survey they use asks firms about usage of AI methods such as natural languange understanding, image recognition, machine learning, and knowledge-based systems, whether these technologies were developed by the firm or a third-party, and the start year of AI usage. They employ IV estimators to account for the possible endogeneity arising from more productive firms are the those investing in AI. The instruments they need are variables correlated with AI use but uncorrelated with productivity (super hard). The instruments they use are sector-level AI use, past innovation expenditure, and resistance to innovation by the firms' workers.

@Brynjolfsson2023 "we study the staggered introduction of a generative AI-based conversational assistant using data from 5,179 customer support agents. Access to the tool increases productivity, as measured by issues resolved per hour, by 14\% on average, including a 34\% improvement for novice and low-skilled workers but with minimal impact on experienced and highly skilled workers. We provide suggestive evidence that the AI model disseminates the best practices of more able workers and helps newer workers move down the experience curve. In addition, we find that AI assistance improves customer sentiment, increases employee retention, and may lead to worker learning. Our results suggest that access to generative AI can increase productivity, with *large heterogeneity in effects across workers.*"

The tool under study is the Generative Pre-Trained Transformer (GPT) family of large language models (LLM) developed by OpenAI. It monitors customers chats and provides real-time suggestions for how to respond. Agents had the option to ignore the GPT's suggestions.

The effects of productivity are highly heterogeneous across agents. Low-skilled and less-experienced workers improved significantly across different measures of productivity. Access to the AI tool helped newer agents move across the experience curve more quickly. In contrast, there were minimal impacts on the productivity of more-skilled more-experienced agents. Importantly, the authors find evidence that AI assitance may decrease the quality of conversations by the most skilled agents.

AI assistance helped agents communicate more effectively even under hostile conversations, but it also made agenst seem mechanical or unauthentic. 

AI assistance helps in the convergence of skill across agents by using data from high-skill workers and helping low-skill workers. Worker contribution to the AI assistance tool is heterogeneous and high-skill workers are not compensated by the data they provide. 

@Jiang2025 find that AI exposure is associated with longer work hours and reduced leisure time. The productivity gains in these markets are captured by consumers or firms. Why? Primarily, because AI complements human labor rather than replacing it, according to the authors. Authors use individual-level time diary data from 2004 to 2023 (American Time Use Survey). AI exposure stems froms ChatGPT shock or broader AI evolution. 

The author use a simple principal-agent model to explain the mechanism of how AI exposure affects the allocation of individuals' time between work and leisure. They identify three main mechanisms: If AI complements human labor enhancing the marginal productivity of the agent, the increase in marginal producivity would lead agents to work longer hours. AI enhances work monitoring leading to increasing work hours. Lastly, in competitive labor markets where workers have limited bargaining power, workers would not be able to extract the benefits of their increased productivity (higher wages or lower work hours).



