## Identification Strategies

The problem is we can't just include a $AI_{jt}$ dummy variable into a production function regression:

$$
y_{jt}=g(k_{jt}, l_{jt}, m_{jt}) + AI_{jt} +\omega_{jt}+\varepsilon_{jt}
$$

because it is likely that $\mathbb{E}[\omega_{jt}|AI]\not=0$. In other words, more productive firms are more likely to choose to use AI.

Low case variables are the logs of the levels $log(Y_{jt})=y_{jt}$.

Here $\omega_{jt}$ represents the persisten part of productivity and $\varepsilon_{jt}$ is the measurement error (or output shocks). It is usually assume that the persistent part of the error term follows a markov process, in particular an AR(1),

$$
\omega_{jt}=h(\omega_{jt-1})+\eta_{jt}
$$



### Approach 1: Are firms using AI more productive?

One strategy is to do what we do with other indicator variables that are endogenous to productivity, like being an exporter. 

In those cases, we exclude the dummy variable from the production function regression,


$$
y_{jt}=g(k_{jt}, l_{jt}, m_{jt}) +\omega_{jt}+\varepsilon_{jt}
$$

We can estimate the production function using GNR(2020), or other method, and productivity. With estimates of firm-level productivity, we can compare the productivity of firms choosing and not choosing to use AI. Of course, here we could not claim a causal effect. This will only serve to test our assumption that AI adopting firms are indeed more likely to display higher productivity.


### Strategy II 

We can think about the model a little bit more. The intuition of the identification in GNR(2020) is that firms choose intermediates after they observe their productivity shock. Because intermediates are flexible (they choose the quantity they want in the current period), then we again have that $\mathbb{E}[\omega_{jt}|M_{jt}]\not=0$.

However, starting from the firm's cost-minimization problem,

$$
\begin{aligned}
\max_{\substack{K_{jt}, L_{jt}, M_{jt} \\ AI_{jt}}} \pi = P_t\mathbb{E}[Y_{jt}]-r_tK_{jt}-w_tL_{jt}-c_tM_{jt} \\
 \text{s.t.} Y_{jt}=G(K_{jt}, L_{jt}, M_{jt})\exp^{\omega_{jt}+\varepsilon_{jt}}
\end{aligned}
$$

Taking the FOC wrt $M_{jt}$, multiplying by $M_{jt}$, dividing by $Y_{jt}= G(K_{jt}, L_{jt}, M_{jt})\exp^{\omega_{jt}+\varepsilon_{jt}}$ and taking logs, we get,

$$
\log\left(\frac{c_tM_{jt}}{P_tY_{jt}}\right)=\log\left(\frac{G_M(\cdot)M_{jt}}{G(\cdot)}\right)+\mathcal{E}-\varepsilon_{jt}
$$

From this equation, we can recover the elasticity of the production function and the error term. Integrating it, we can recover the production function up to an unknown constant depending on $K_{jt}$ and $L_{jt}$. Then using the moments generated by the Markov process of productivity, we can recover the remaining constants. Having the production function and the error term, $\omega_{jt}$ can be recovered at the firm-level with the difference.

The question for us is, how does the decision of the firms in adopting AI look like? When do they do this? Can we leverage from modeling this decision to identify the effect of adopting AI on productivity.

For example, we can start assuming that firms choose to adopt AI in the current period (whatever the data tell us a period is) before knowing their productivity shock in the current period. In other words, a firm chooses $AI=1$ iff,

$$
\mathbb{E}[\pi|AI=1] > \mathbb{E}[\pi|AI=0] 
$$

A firm would not adopt AI $AI=0$ if

$$
\mathbb{E}[\pi|AI=1] \le \mathbb{E}[\pi|AI=0] 
$$

Of course, simplifying these inequalities we get that firms adopt AI if

$$
\mathbb{E}[\omega_{jt}|AI=1] > \mathbb{E}[\omega_{jt}|AI=0] 
$$

and they do not kwow if

$$
\mathbb{E}[\omega_{jt}|AI=1] \le \mathbb{E}[\omega_{jt}|AI=0] 
$$

It makes sense that firms can flexibly adopt AI because the cost of using generative AI drastically dropped after the release of ChatGPT. Of course, specialized generative AI tools will take longer, but we can restrict the study to the first wave of generative AI, looking at the period close to the release of ChatGPT.

Following our assumptions, we can then have many instruments. We can use $k_{jt}$ as instrument. It will be correlated with the adopting AI, because firms with higher computational power and better IT infrastructure would more easily adopt AI, but because capital is a predetermined input, it is uncorrelated with the current productivity shock. 

The same argument works for labor. Skilled labor $l_{jt}$ might be correlated with AI adoption, but it will be uncorrelated with current productivity shock.

Other instruments we could use are the intermediates used last period $m_{jt}$, the capital and labor used the previous period, productivity used two periods ago.